import { Achievement, AchievementCategory } from '../engine/types/game';

export const achievementCategories: Array<'All' | AchievementCategory> = ['All', 'Progression', 'Skill', 'Daily', 'Stars', 'Streak', 'Exploration', 'Mastery'];

export const achievementCatalog: Achievement[] = [
  { id: 'first_escape', title: 'First Escape', description: 'Complete your first puzzle.', icon: 'N1', category: 'Progression', progress: 0, target: 1, unlocked: false, reward: { type: 'hint', amount: 1 } },
  { id: 'path_finder', title: 'Path Finder', description: 'Complete 25 levels.', icon: '25', category: 'Progression', progress: 0, target: 25, unlocked: false, reward: { type: 'booster', booster: 'reveal', amount: 1 } },
  { id: 'route_master', title: 'Route Master', description: 'Complete 100 levels.', icon: '100', category: 'Progression', progress: 0, target: 100, unlocked: false, reward: { type: 'hint', amount: 3 } },
  { id: 'nexa_veteran', title: 'Nexa Veteran', description: 'Complete 250 levels.', icon: '250', category: 'Progression', progress: 0, target: 250, unlocked: false, reward: { type: 'booster', booster: 'undo', amount: 2 } },
  { id: 'arrownexa_master', title: 'ArrowNexa Master', description: 'Complete all 500 levels.', icon: '500', category: 'Mastery', progress: 0, target: 500, unlocked: false, reward: { type: 'hint', amount: 5 } },
  { id: 'flawless', title: 'Flawless', description: 'Complete a level with 0 mistakes.', icon: '0M', category: 'Skill', progress: 0, target: 1, unlocked: false },
  { id: 'no_help_needed', title: 'No Help Needed', description: 'Complete 10 levels without hints.', icon: 'NH', category: 'Skill', progress: 0, target: 10, unlocked: false, reward: { type: 'hint', amount: 2 } },
  { id: 'untouchable', title: 'Untouchable', description: 'Earn 3 stars on a Hard level.', icon: 'H3', category: 'Skill', progress: 0, target: 1, unlocked: false },
  { id: 'expert_mind', title: 'Expert Mind', description: 'Complete an Expert puzzle without a hint.', icon: 'EX', category: 'Skill', progress: 0, target: 1, unlocked: false, reward: { type: 'booster', booster: 'reveal', amount: 1 } },
  { id: 'perfect_run', title: 'Perfect Run', description: 'Earn 3 stars on 25 levels.', icon: 'PR', category: 'Mastery', progress: 0, target: 25, unlocked: false, reward: { type: 'booster', booster: 'undo', amount: 1 } },
  { id: 'stars_100', title: '100 Stars', description: 'Collect 100 total stars.', icon: '100', category: 'Stars', progress: 0, target: 100, unlocked: false, reward: { type: 'hint', amount: 1 } },
  { id: 'stars_250', title: '250 Stars', description: 'Collect 250 total stars.', icon: '250', category: 'Stars', progress: 0, target: 250, unlocked: false, reward: { type: 'hint', amount: 2 } },
  { id: 'stars_500', title: '500 Stars', description: 'Collect 500 total stars.', icon: '500', category: 'Stars', progress: 0, target: 500, unlocked: false, reward: { type: 'booster', booster: 'reveal', amount: 2 } },
  { id: 'stars_1000', title: '1000 Stars', description: 'Collect 1000 total stars.', icon: '1K', category: 'Stars', progress: 0, target: 1000, unlocked: false, reward: { type: 'booster', booster: 'undo', amount: 2 } },
  { id: 'stars_1500', title: '1500 Stars', description: 'Collect every possible star.', icon: 'MAX', category: 'Mastery', progress: 0, target: 1500, unlocked: false, reward: { type: 'hint', amount: 5 } },
  { id: 'daily_starter', title: 'Daily Starter', description: 'Complete your first Daily Challenge.', icon: 'D1', category: 'Daily', progress: 0, target: 1, unlocked: false, reward: { type: 'hint', amount: 1 } },
  { id: 'dedicated_solver', title: 'Dedicated Solver', description: 'Complete 7 Daily Challenges.', icon: 'D7', category: 'Daily', progress: 0, target: 7, unlocked: false, reward: { type: 'booster', booster: 'reveal', amount: 1 } },
  { id: 'daily_master', title: 'Daily Master', description: 'Complete 30 Daily Challenges.', icon: 'D30', category: 'Daily', progress: 0, target: 30, unlocked: false, reward: { type: 'hint', amount: 3 } },
  { id: 'perfect_day', title: 'Perfect Day', description: 'Get a perfect Daily Challenge.', icon: 'PD', category: 'Daily', progress: 0, target: 1, unlocked: false, reward: { type: 'hint', amount: 1 } },
  { id: 'seven_in_a_row', title: 'Seven in a Row', description: 'Reach a 7-day Challenge Streak.', icon: '7R', category: 'Streak', progress: 0, target: 7, unlocked: false, reward: { type: 'booster', booster: 'undo', amount: 1 } },
  { id: 'nexa_rank_5', title: 'Nexa Rank 5', description: 'Reach Nexa Rank 5.', icon: 'R5', category: 'Progression', progress: 0, target: 5, unlocked: false },
  { id: 'nexa_rank_10', title: 'Nexa Rank 10', description: 'Reach Nexa Rank 10.', icon: 'R10', category: 'Progression', progress: 0, target: 10, unlocked: false, reward: { type: 'hint', amount: 2 } },
  { id: 'nexa_rank_25', title: 'Nexa Rank 25', description: 'Reach Nexa Rank 25.', icon: 'R25', category: 'Progression', progress: 0, target: 25, unlocked: false, reward: { type: 'booster', booster: 'reveal', amount: 1 } },
  { id: 'nexa_rank_50', title: 'Nexa Rank 50', description: 'Reach Nexa Rank 50.', icon: 'R50', category: 'Mastery', progress: 0, target: 50, unlocked: false, reward: { type: 'hint', amount: 4 } },
  { id: 'arrow_cleaner_bronze', title: 'Arrow Cleaner', description: 'Remove 500 arrows.', icon: 'AC', category: 'Exploration', tier: 'Bronze', progress: 0, target: 500, unlocked: false, reward: { type: 'hint', amount: 1 } },
  { id: 'arrow_cleaner_silver', title: 'Arrow Cleaner', description: 'Remove 2,500 arrows.', icon: 'AC', category: 'Exploration', tier: 'Silver', progress: 0, target: 2500, unlocked: false, reward: { type: 'booster', booster: 'undo', amount: 1 } },
  { id: 'arrow_cleaner_gold', title: 'Arrow Cleaner', description: 'Remove 10,000 arrows.', icon: 'AC', category: 'Exploration', tier: 'Gold', progress: 0, target: 10000, unlocked: false, reward: { type: 'booster', booster: 'reveal', amount: 2 } },
  { id: 'arrow_cleaner_master', title: 'Arrow Cleaner', description: 'Remove 25,000 arrows.', icon: 'AC', category: 'Mastery', tier: 'Master', progress: 0, target: 25000, unlocked: false, reward: { type: 'hint', amount: 5 } },
  { id: 'hidden_comeback', title: 'Quiet Return', description: 'Come back and finish a level after a break.', icon: '??', category: 'Exploration', hidden: true, progress: 0, target: 1, unlocked: false },
];
