import { Achievement } from '../engine/types/game';

export const achievementCatalog: Achievement[] = [
  { id: 'first_escape', title: 'First Escape', description: 'Complete your first puzzle.', icon: 'N1', progress: 0, target: 1, unlocked: false },
  { id: 'getting_started', title: 'Getting Started', description: 'Complete 10 levels.', icon: '10', progress: 0, target: 10, unlocked: false },
  { id: 'arrow_apprentice', title: 'Arrow Apprentice', description: 'Complete 25 levels.', icon: '25', progress: 0, target: 25, unlocked: false },
  { id: 'arrow_expert', title: 'Arrow Expert', description: 'Complete 100 levels.', icon: '100', progress: 0, target: 100, unlocked: false },
  { id: 'perfectionist', title: 'Perfectionist', description: 'Complete a level without mistakes.', icon: '3S', progress: 0, target: 1, unlocked: false },
  { id: 'no_help', title: 'No Help Needed', description: 'Complete a difficult level without hints.', icon: 'NH', progress: 0, target: 1, unlocked: false },
  { id: 'hard_solver', title: 'Hard Solver', description: 'Complete your first Hard puzzle.', icon: 'H', progress: 0, target: 1, unlocked: false },
  { id: 'expert_escape', title: 'Expert Escape', description: 'Complete an Expert puzzle.', icon: 'E', progress: 0, target: 1, unlocked: false },
  { id: 'streak_master', title: 'Streak Master', description: 'Maintain a 7-day streak.', icon: '7D', progress: 0, target: 7, unlocked: false },
  { id: 'arrow_cleaner', title: 'Arrow Cleaner', description: 'Remove 1,000 arrows.', icon: '1K', progress: 0, target: 1000, unlocked: false },
  { id: 'perfect_escape', title: 'Perfect Escape', description: 'Complete a level with 3 stars.', icon: '3S', progress: 0, target: 1, unlocked: false },
  { id: 'untouched', title: 'Untouched', description: 'Complete 10 levels without mistakes.', icon: '0M', progress: 0, target: 10, unlocked: false },
  { id: 'thinker', title: 'Thinker', description: 'Complete a Hard level without hints.', icon: 'TH', progress: 0, target: 1, unlocked: false },
  { id: 'survivor', title: 'Survivor', description: 'Complete a level with 1 life remaining.', icon: '1L', progress: 0, target: 1, unlocked: false },
  { id: 'hint_saver', title: 'Hint Saver', description: 'Complete 20 levels without hints.', icon: 'HS', progress: 0, target: 20, unlocked: false },
  { id: 'comeback', title: 'Comeback', description: 'Use Extra Life and complete the level.', icon: 'CB', progress: 0, target: 1, unlocked: false },
  { id: 'chapter_one', title: 'Chapter One', description: 'Complete Chapter 1.', icon: 'C1', progress: 0, target: 1, unlocked: false },
  { id: 'star_collector', title: 'Star Collector', description: 'Collect 100 stars.', icon: 'SC', progress: 0, target: 100, unlocked: false },
  { id: 'star_master', title: 'Star Master', description: 'Collect 500 stars.', icon: 'SM', progress: 0, target: 500, unlocked: false },
  { id: 'perfect_path', title: 'Perfect Path', description: 'Earn 3 stars on 25 levels.', icon: 'PP', progress: 0, target: 25, unlocked: false },
  { id: 'nexa_rising', title: 'Nexa Rising', description: 'Reach Nexa Rank 10.', icon: 'R10', progress: 0, target: 10, unlocked: false },
  { id: 'nexa_master', title: 'Nexa Master', description: 'Reach Nexa Rank 25.', icon: 'R25', progress: 0, target: 25, unlocked: false },
  { id: 'dedicated', title: 'Dedicated', description: 'Reach a 7-day streak.', icon: 'D7', progress: 0, target: 7, unlocked: false },
  { id: 'unstoppable', title: 'Unstoppable', description: 'Reach a 30-day streak.', icon: 'D30', progress: 0, target: 30, unlocked: false },
];
